# Generated by Django 5.0.3 on 2024-05-03 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReconApp', '0002_result_detailresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissingInvoiceInOcc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('flight', models.CharField(max_length=100)),
                ('departure', models.CharField(max_length=100)),
                ('arrival', models.CharField(max_length=100)),
                ('registration', models.CharField(max_length=100)),
                ('uplift_in_lts', models.FloatField(default=0)),
                ('invoice_no', models.CharField(max_length=100)),
                ('fuel_agent', models.CharField(max_length=100)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missing_invoices_in_occ', to='ReconApp.result')),
            ],
        ),
        migrations.CreateModel(
            name='MissingInvoiceInVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('flight', models.CharField(max_length=100)),
                ('departure', models.CharField(max_length=100)),
                ('arrival', models.CharField(max_length=100)),
                ('registration', models.CharField(max_length=100)),
                ('uplift_in_lts', models.FloatField(default=0)),
                ('invoice_no', models.CharField(max_length=100)),
                ('fuel_agent', models.CharField(max_length=100)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missing_invoices_in_vendor', to='ReconApp.result')),
            ],
        ),
    ]
