# Generated by Django 5.0.3 on 2024-04-03 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReconApp', '0003_alter_reconsiliasi_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissingInvoiceOcc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('flight', models.CharField(max_length=50)),
                ('departure', models.CharField(max_length=100)),
                ('arrival', models.CharField(max_length=100)),
                ('registration', models.CharField(max_length=20)),
                ('uplift_in_lts', models.FloatField()),
                ('invoice_no', models.CharField(max_length=100)),
                ('vendor', models.CharField(max_length=100)),
            ],
        ),
    ]
