# Generated by Django 5.0.3 on 2024-05-21 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ReconApp', '0004_delete_missinginvoice_delete_missinginvoiceocc_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MissingInvoiceInOcc',
        ),
    ]
