# Generated by Django 5.0.3 on 2024-04-03 03:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReconApp', '0004_missinginvoiceocc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='missinginvoice',
            name='vendor',
        ),
        migrations.AddField(
            model_name='missinginvoice',
            name='Vendor',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
    ]
