# Generated by Django 5.0.3 on 2024-03-23 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelOcc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_occ', models.DateField()),
                ('flight_occ', models.CharField(max_length=50)),
                ('departure_occ', models.CharField(max_length=100)),
                ('arrival_occ', models.CharField(max_length=100)),
                ('registration_occ', models.CharField(max_length=20)),
                ('uplift_in_lts_occ', models.FloatField()),
                ('uplift_in_usg_occ', models.FloatField()),
                ('invoice_no_occ', models.CharField(max_length=100)),
                ('vendor_occ', models.CharField(blank=True, choices=[('pertamina', 'Pertamina'), ('shell', 'Shell'), ('total', 'Total'), ('chevron', 'Chevron'), ('petronas', 'Petronas'), ('air_bp', 'Air BP')], max_length=100, null=True)),
            ],
        ),
    ]
