# Generated by Django 5.0.3 on 2024-03-23 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OCCApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fuelocc',
            old_name='arrival_occ',
            new_name='Arr',
        ),
        migrations.RenameField(
            model_name='fuelocc',
            old_name='date_occ',
            new_name='Date',
        ),
        migrations.RenameField(
            model_name='fuelocc',
            old_name='departure_occ',
            new_name='Dep',
        ),
        migrations.RenameField(
            model_name='fuelocc',
            old_name='flight_occ',
            new_name='Flight',
        ),
        migrations.RenameField(
            model_name='fuelocc',
            old_name='invoice_no_occ',
            new_name='Invoice',
        ),
        migrations.RenameField(
            model_name='fuelocc',
            old_name='registration_occ',
            new_name='Reg',
        ),
        migrations.RenameField(
            model_name='fuelocc',
            old_name='uplift_in_lts_occ',
            new_name='Uplift_in_Lts',
        ),
        migrations.RenameField(
            model_name='fuelocc',
            old_name='uplift_in_usg_occ',
            new_name='Uplift_in_Usg',
        ),
        migrations.RenameField(
            model_name='fuelocc',
            old_name='vendor_occ',
            new_name='Vendor',
        ),
    ]
