# Generated by Django 5.0.3 on 2024-04-01 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OCCApp', '0002_rename_arrival_occ_fuelocc_arr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelocc',
            name='Vendor',
            field=models.CharField(blank=True, choices=[('pertamina', 'Pertamina'), ('petronas_dagangan', 'Petronas Dagangan'), ('pttor', 'PTTOR'), ('bafs', 'BAFS'), ('petronas_dagangan_berhad', 'Petronas Dagangan Berhad'), ('shell', 'Shell'), ('petron', 'Petron'), ('airbp', 'AIRBP'), ('ptt_public_co_ltd', 'PTT Public Co. Ltd'), ('singapore_petroleum_company_limited', 'Singapore Petroleum Company Limited'), ('shell_malaysia_trading', 'Shell Malaysia Trading')], max_length=100, null=True),
        ),
    ]
