# Generated by Django 5.0.3 on 2024-05-21 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OCCApp', '0003_alter_fuelocc_vendor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FuelOcc',
        ),
    ]
