# Generated by Django 5.0.3 on 2024-03-23 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ven', models.DateField()),
                ('flight_ven', models.CharField(max_length=50)),
                ('departure_ven', models.CharField(max_length=100)),
                ('arrival_ven', models.CharField(max_length=100)),
                ('registration_ven', models.CharField(max_length=20)),
                ('uplift_in_lts_ven', models.FloatField()),
                ('uplift_in_usg_ven', models.FloatField()),
                ('invoice_no_ven', models.CharField(max_length=100)),
                ('vendor_name', models.CharField(blank=True, choices=[('pertamina', 'Pertamina'), ('shell', 'Shell'), ('total', 'Total'), ('chevron', 'Chevron'), ('petronas', 'Petronas'), ('air_bp', 'Air BP')], max_length=100, null=True)),
            ],
        ),
    ]
