# Generated by Django 5.0.3 on 2024-03-23 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VendorApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fuelvendor',
            old_name='arrival_ven',
            new_name='Arr',
        ),
        migrations.RenameField(
            model_name='fuelvendor',
            old_name='date_ven',
            new_name='Date',
        ),
        migrations.RenameField(
            model_name='fuelvendor',
            old_name='departure_ven',
            new_name='Dep',
        ),
        migrations.RenameField(
            model_name='fuelvendor',
            old_name='flight_ven',
            new_name='Flight',
        ),
        migrations.RenameField(
            model_name='fuelvendor',
            old_name='invoice_no_ven',
            new_name='Invoice',
        ),
        migrations.RenameField(
            model_name='fuelvendor',
            old_name='registration_ven',
            new_name='Reg',
        ),
        migrations.RenameField(
            model_name='fuelvendor',
            old_name='uplift_in_lts_ven',
            new_name='Uplift_in_Lts',
        ),
        migrations.RenameField(
            model_name='fuelvendor',
            old_name='uplift_in_usg_ven',
            new_name='Uplift_in_Usg',
        ),
        migrations.RenameField(
            model_name='fuelvendor',
            old_name='vendor_name',
            new_name='Vendor',
        ),
    ]
