# Generated by Django 5.0.3 on 2024-04-01 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VendorApp', '0003_remove_fuelvendor_uplift_in_usg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelvendor',
            name='Vendor',
            field=models.CharField(blank=True, choices=[('Pertamina', 'Pertamina'), ('Petronas Dagangan', 'Petronas Dagangan'), ('PTTOR', 'PTTOR'), ('BAFS', 'BAFS'), ('Petronas Dagangan Berhad', 'Petronas Dagangan Berhad'), ('Shell', 'Shell'), ('Petron', 'Petron'), ('AIRBP', 'AIRBP'), ('PTT Public Co. Ltd', 'PTT Public Co. Ltd'), ('Singapore Petroleum Company Limited', 'Singapore Petroleum Company Limited'), ('Shell Malaysia Trading', 'Shell Malaysia Trading')], max_length=100, null=True),
        ),
    ]
