# Generated by Django 5.0.3 on 2024-04-03 02:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VendorApp', '0004_alter_fuelvendor_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelvendor',
            name='Vendor',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
    ]
