# Generated by Django 5.0.3 on 2024-05-22 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VendorApp', '0005_alter_fuelvendor_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelvendor',
            name='Invoice',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
